apiVersion: v1
kind: Namespace
metadata:
  name: mcp-search-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mflix-search-app
  namespace: mcp-search-app
  labels:
    app: mflix-search-app
spec:
  selector:
    matchLabels:
      app: mflix-search-app
  replicas: 2
  template:
    metadata:
      labels:
        app: mflix-search-app
    spec:
      serviceAccountName: mcp-search-sa
      containers:
      - name: mflix-search-container
        image: <<Image URI>>
        env:
        - name: MCP_TOOL_NAME
          value: "MflixSearch"
        - name: MONGO_CREDS
          value: "demo1"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-search-app
  namespace: mcp-search-app
  labels:
    app: airbnb-search-app
spec:
  selector:
    matchLabels:
      app: airbnb-search-app
  replicas: 2
  template:
    metadata:
      labels:
        app: airbnb-search-app
    spec:
      serviceAccountName: mcp-search-sa
      containers:
      - name: airbnb-search-container
        image: <<Image URI>>
        env:
        - name: MCP_TOOL_NAME
          value: "AirbnbSearch"
        - name: MONGO_CREDS
          value: "demo1"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: mcp-search-app
  name: mflix-search-service
  labels:
    app: mflix-search-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /mflixSearch/health
spec:
  type: NodePort
  selector:
    app: mflix-search-app
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: mcp-search-app
  name: airbnb-search-service
  labels:
    app: airbnb-search-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /AirbnbSearch/health
spec:
  type: NodePort
  selector:
    app: airbnb-search-app
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-search-ingress
  namespace: mcp-search-app
  labels:
    app: mcp-search-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
spec:
  rules:
    - http:
        paths:
          - path: /mflixSearch
            pathType: Prefix
            backend:
              service:
                name: mflix-search-service
                port:
                  number: 8000                        
          - path: /AirbnbSearch
            pathType: Prefix
            backend:
              service:
                name: airbnb-search-service
                port:
                  number: 8000
